# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/PDB101',
                'doc_host': 'https://roshkjr.github.io',
                'git_url': 'https://github.com/roshkjr/PDB101',
                'lib_path': 'PDB101'},
  'syms': {'PDB101.core': {'PDB101.core.foo': ('core.html#foo', 'PDB101/core.py')}}}
